### ISSUE TITLE
bed format error when testing on amplicon & ref on other viruses

### ISSUE THREAD

**Issue by Krysasp** [Psy-Fer/interARTIC#71]
Hi there, thank you for creating this amazing tools !
I recently work on other viruses and try to customize my own primers in bed format, i flagged correctly "_LEFT" and "_RIGHT" to the scheme. But somewhat still getting this error:

Traceback (most recent call last):
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ihcm-ubuntu/interartic_bin/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ihcm-ubuntu/interartic_bin/main.py", line 940, in parameters
    new_job = qSys.newJob(job_name, input_folder, read_file, primer_scheme_dir, primer_scheme, primer_type, output_folder, normalise, num_threads, pipeline, min_length, max_length, bwa, skip_nanopolish, dry_run, override_data, num_samples, guppyplex, barcode_type, input_name, csv_filepath, primer_select, input_name)
  File "/home/ihcm-ubuntu/interartic_bin/src/system.py", line 25, in newJob
    return Job(job_name, input_folder, read_file, primer_scheme_dir, primer_scheme, primer_type, output_folder, normalise, num_threads, pipeline, min_length, max_length, bwa, skip_nanopolish, dry_run, override_data, num_samples, guppyplex, barcode_type, run_name, csv_file, primer_select, input_name)
  File "/home/ihcm-ubuntu/interartic_bin/src/job.py", line 42, in __init__
    self._plot_cmd = self.__generatePlotCmd()
  File "/home/ihcm-ubuntu/interartic_bin/src/job.py", line 520, in __generatePlotCmd
    plot_cmd = plot_cmd + "; covarPlots.py -v {} -d1 {} -d2 {} -b {}".format(vcf_file, depth1, depth2, bed_file) + " >> " + self._output_folder + "/all_cmds_log.txt 2>>" + self._output_folder + "/all_cmds_log.txt"
UnboundLocalError: local variable 'bed_file' referenced before assignment

Is anyone know what error could i have committed?

**Comment by Krysasp** [comment]
issue solved: turns out I ran into some malfunction bed files..

**Comment by ShawnSimp** [comment]
@Krysasp can I get some more clarity on how you solved this issue? i'm get the same " UnboundLocalError: local variable 'bed_file' referenced before assignment " error at the moment

**Comment by Psy-Fer** [comment]
Hello @ShawnSimp,

Could you drop me the full error message?

Could be your bed wasn't picked up along with a certain set of circumstances my error handling doesn't pick up, so throwing that rather than actually doing something useful for you.

Please let me know and I'll try and help/fix it.

Cheers,
James
